name: akademi_bootcamp
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  # STATE_MANAGEMENT
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.3.0
  mobx: ^2.2.0
  provider: ^6.0.5
  # FIREBASE
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  google_sign_in: ^6.1.4
  firebase_storage: ^11.2.4
  cloud_firestore: ^4.8.2
  # UTIL
  google_fonts: ^4.0.4
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  flutter_slidable: ^3.0.0
  flutter:
    sdk: flutter
  # LOCATION
  latlong2: ^0.8.2
  flutter_map: ^4.0.0
  geolocator: ^9.0.2
  # API
  http: ^0.13.0
  flutter_facebook_auth: ^5.0.11
  html: ^0.15.4
  # LANG
  intl: ^0.18.1
  timezone: ^0.9.2
  # STORAGE
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0
  # NOTIFICATION
  flutter_local_notifications: ^15.1.0+1
  cached_network_image: ^3.2.3
  # OTHER
  image_picker: ^1.0.0
  url_launcher: ^6.1.11
  connectivity_plus: ^4.0.1
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.5 

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/