class TextConstants {
  TextConstants._();
  static late final TextConstants instance = TextConstants._();

  static final String appName = "ActivitIST";
  static final String yourFavEvents = "FAVORİ ETKİNLİKLERİN";
  static final String inYourPackage = "CEBİNDE";
  static final String via = "Bu uygulamadaki etkinlik verileri Etkinlik.io tarafından sağlanmaktadır.";
  static final String resetPassword = "Şifreni Yenile";
  static final String email = "Email";
  static final String password = "Şifre";
  static final String name = "Ad";
  static final String logIn = "Giriş Yap";
  static final String signIn = "Kayıt Ol";
  static final String logOut = "Çıkış Yap";
  static final String continueLabel = "Devam Et";
  static final String typeMessage = "Mesaj yazın";
  static final String forgotPassword = "Şifremi Unuttum";
  static final String sendPasswordResetLink = "Şifre Yenileme Linki Gönder";
  static final String search = "Ara...";
  static final String seeAll = "Hepsini Gör";
  static final String activitiesOf = "Aktiviteleri";
  static final String editProfile = "Profili Düzenle";
  static final String editPhoto = "Fotoğrafı Düzenle";
  static final String city = "Şehir";
  static final String gender = "Cinsiyet";
  static final String myGroups = "Gruplarım";
  static final String eventInfo = "Etkinlik Bilgisi";
  static final String placeInfo = "Mekan Bilgisi";
  static final String myFav = "Favorilerim";
  static final String buyTicket = 'Bilet Satın Al';
  static final String errorMessage = 'Bir hata oluştu';
  static final String pickGallery = 'Galeriden Seç';
  static final String pickCamera = 'Fotoğraf Çek';
  static final String removeCurrentPhoto = 'Mevcut Fotoğrafı Kaldır';
  static final String copyright = 'ActivitIST © 2023';
  static final String remove = 'Kaldır';
  static final String sureMessageAboutRemovingPhoto = "Fotoğrafı kaldırmak istediğine emin misin?";
  static final String cancel = 'Vazgeç';
}
